version: '3.7'  

services:
  web: 
    image: imagenfront
    build: 
      context: ./voltafront/
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    container_name: contenedorfront
    entrypoint: ["npm", "start"]


  back: 
    image: imagenback
    build: 
      context: ./BACK/back.volta/
      dockerfile: Dockerfile
    ports:
      - "20251:8080"
    container_name: contenedorback
    entrypoint: ["java", "-jar", "app.jar"]
