version: '3.7'  

services:
  web: 
    image: imagenfront
    build: 
      context: ./voltafront/
      dockerfile: Dockerfile
    ports:
      - "20250:3000"
    container_name: contenedorfront
    entrypoint: ["npm", "start"]
    




  back: 
    image: imagenback
    build: 
      context: ./BACK/back.volta/
      dockerfile: Dockerfile
    ports:
      - "20251:8080"
    container_name: contenedorback
    entrypoint: ["java", "-jar", "app.jar"]
    
  

  bbdd:
    image: imagenbbdd
    ports:
      - "20253:1433"
    build: 
      context: ./BBDD/
      dockerfile: Dockerfile
    container_name: contenedorbbdd
    entrypoint: ["/bin/bash", "-c", "/usr/src/app/init-db.sh & /opt/mssql/bin/sqlservr"]
